image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - "cd Backend-Spring-Boot"
    - mvn clean
    - echo "Compiling the code."
    - mvn compile
    - echo "Compile complete."

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - "cd Backend-Spring-Boot"    
    - echo "Running unit tests... This will take about 60 seconds."
    - mvn test

package-job:      # This job runs in the package stage.
  stage: package  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - "cd Backend-Spring-Boot"    
    - echo "Packaging application..."
    - mvn package
    - echo "Application successfully packaged."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when jobs in the package stage complete successfully.
  environment: production
  script:
    - "cd Backend-Spring-Boot"
    - echo "Deploying application..."
    - echo "Application successfully deployed."
